### ISSUE TITLE
Swift 5 support

### ISSUE THREAD

**Issue by zapko** [wingify/vwo-ios-sdk#11]
Hey guys!

When do you plan to migrate to Swift 5? It's almost two years since it was released. What are the obstacles impending the migration?

**Comment by sanyamjain65** [comment]
Hi Zapko!!
Right now we are not sure but this is in our roadmap. We will keep you updated.

**Comment by RuffRyders** [comment]
+++

**Comment by n-vart** [comment]
@sanyamjain65 any news? How much time do you need for implement spm support ? 
Really need it

**Comment by softvar** [comment]
Hey everyone,

We heard you. We're finally on our way to support **Swift 5** shortly 🙌 

@RuffRyders _spm support_ will require a good amount of refactoring. We will prioritize that too soon :)
Could you please raise the same on our VWO Support System(support@vwo.com) so that it gets more visibility? 

Thanks for your patience.

**Comment by ParveshChauhan** [comment]
Hey everyone,

Now SPM is also supported in master branch. @n-vart 
@zapko Closing this issue becauseSDK also support swift 5 version.
